In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name": ['Yohan','Ravi','Anu','Teja','Kiran'],
    "Age": [20, 21, 19, 22, 23],
    'Marks': [85, 90, 75, 60, 95]
    
})
print(df)

    Name  Age  Marks
0  Yohan   20     85
1   Ravi   21     90
2    Anu   19     75
3   Teja   22     60
4  Kiran   23     95

In [4]:
#select column
print(df['Name'])
#select multiple columns
print("\n",df[["Name","Age"]])

0    Yohan
1     Ravi
2      Anu
3     Teja
4    Kiran
Name: Name, dtype: object

     Name  Age
0  Yohan   20
1   Ravi   21
2    Anu   19
3   Teja   22
4  Kiran   23

In [5]:
print(df.iloc[0])   # First row by index position
print(df.loc[2])    # Row by label (index value)

Name     Yohan
Age         20
Marks       85
Name: 0, dtype: object
Name     Anu
Age       19
Marks     75
Name: 2, dtype: object

In [6]:
print(df[1:4])   # Rows from index 1 to 3

   Name  Age  Marks
1  Ravi   21     90
2   Anu   19     75
3  Teja   22     60

In [7]:
"""Conditional Filtering"""

'Conditional Filtering'

In [8]:
# Students with marks > 80
higher_rankers = df[df["Marks"] >80]
print(higher_rankers)

    Name  Age  Marks
0  Yohan   20     85
1   Ravi   21     90
4  Kiran   23     95

In [9]:
# Students younger than 22 and marks > 70
filtered = df[(df["Age"] < 22) & (df["Marks"] > 70)]
print(filtered)

    Name  Age  Marks
0  Yohan   20     85
1   Ravi   21     90
2    Anu   19     75

In [10]:
"Handling Missing Values (NaN)"

'Handling Missing Values (NaN)'

In [14]:
data = {
    'Name': ['Yohan', 'Ravi', 'Anu', 'Teja'],
    'Age': [20, None, 19, 22],
    'Marks': [85, 90, None, 60]
}

df = pd.DataFrame(data)
print(df)

    Name   Age  Marks
0  Yohan  20.0   85.0
1   Ravi   NaN   90.0
2    Anu  19.0    NaN
3   Teja  22.0   60.0

In [15]:
"Fill missing values"

'Fill missing values'

In [16]:
# print(df.isnull())

In [17]:
# print(df.isnull().sum())

In [22]:
df.fillna({'Age': df['Age'].mean()},inplace=True)
print(df)

    Name        Age  Marks
0  Yohan  20.000000   85.0
1   Ravi  20.333333   90.0
2    Anu  19.000000    NaN
3   Teja  22.000000   60.0

In [24]:
df.fillna({'Marks': 0}, inplace=True)
print(df)

    Name        Age  Marks
0  Yohan  20.000000   85.0
1   Ravi  20.333333   90.0
2    Anu  19.000000    0.0
3   Teja  22.000000   60.0

In [25]:
df.rename(columns={'Marks': 'Score'}, inplace=True) #Rename column
df.drop('Age', axis=1, inplace=True)  # Drop a column
print(df)

    Name  Score
0  Yohan   85.0
1   Ravi   90.0
2    Anu    0.0
3   Teja   60.0

In [26]:
df.sort_values(by='Score', ascending=False) #sort by score

    Name  Score
1   Ravi   90.0
0  Yohan   85.0
3   Teja   60.0
2    Anu    0.0

In [27]:
df.sort_values(by=['Score', 'Name'])

    Name  Score
2    Anu    0.0
3   Teja   60.0
0  Yohan   85.0
1   Ravi   90.0

In [30]:
data = {
    'Name': ['Ram', 'Krish', 'Latha', 'Hari', 'Mani'],
    'Age': [23, None, 21, 25, 22],
    'Department': ['IT', 'HR', 'Finance', None, 'IT'],
    'Salary': [50000, 45000, None, 52000, 48000]
}
df =pd.DataFrame(data)

print(df)

    Name   Age Department   Salary
0    Ram  23.0         IT  50000.0
1  Krish   NaN         HR  45000.0
2  Latha  21.0    Finance      NaN
3   Hari  25.0       None  52000.0
4   Mani  22.0         IT  48000.0

In [31]:
# Tasks:
# 1. Display names of employees from the 'IT' department
# 2. Fill missing Salary with average salary
# 3. Drop rows with missing Department
# 4. Rename 'Department' → 'Dept'
# 5. Sort employees by Salary in descending order

In [38]:
emp_it = df.loc[df['Department'] == 'IT']
print(emp_it['Name'])

0     Ram
4    Mani
Name: Name, dtype: object

In [40]:
df.fillna({'Salary': df['Salary'].mean()}, inplace=True)
print(df)

    Name   Age Department   Salary
0    Ram  23.0         IT  50000.0
1  Krish   NaN         HR  45000.0
2  Latha  21.0    Finance  48750.0
3   Hari  25.0       None  52000.0
4   Mani  22.0         IT  48000.0

In [47]:
df.dropna(subset=['Department'])

    Name   Age Department   Salary
0    Ram  23.0         IT  50000.0
1  Krish   NaN         HR  45000.0
2  Latha  21.0    Finance  48750.0
4   Mani  22.0         IT  48000.0

In [49]:
df.rename(columns={'Department': 'Dept'}, inplace=True)
print(df)

    Name   Age     Dept   Salary
0    Ram  23.0       IT  50000.0
1  Krish   NaN       HR  45000.0
2  Latha  21.0  Finance  48750.0
3   Hari  25.0     None  52000.0
4   Mani  22.0       IT  48000.0

In [50]:
df.sort_values(by="Salary", ascending=False)

    Name   Age     Dept   Salary
3   Hari  25.0     None  52000.0
0    Ram  23.0       IT  50000.0
2  Latha  21.0  Finance  48750.0
4   Mani  22.0       IT  48000.0
1  Krish   NaN       HR  45000.0